version: '3'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    volumes:
      - wp-data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: "4096"

networks:
  inception:
    driver: bridge

volumes:
  wp-data:
    driver: local
  db-data:
    driver: local