version: '3'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:

volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/grigory/bteak/data/wp
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/grigory/bteak/data/db