services:

  nginx:
    build: containers/nginx/
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  mariadb:
    build: containers/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql
    restart: "no"

networks:
  inception:
    name: inception

volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/grigory/bteak/data/wp
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/grigory/bteak/data/db